import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>随便の前端技术堆积站</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="author" content={"rNLKJA & kwitter"}></meta>
      </Head>

      <main className={styles.main}>
        <div className="container">
          <h1>欢迎访问 随便の前端技术堆积站</h1>
          <h2>
            {"作者: "}
            <a href="https://github.com/chuangyu-hscy">rNLKJA</a>,
            <a href="https://github.com/kwitter777">kwitter777</a>
          </h2>

          <p>
            Back-End Github Repo:
            <a href="https://github.com/chuangyu-hscy/-">
              https://github.com/chuangyu-hscy/-
            </a>
          </p>

          <p>
            Front-End Github Repo:
            <a href="https://github.com/chuangyu-hscy/--">
              https://github.com/chuangyu-hscy/--
            </a>
          </p>
          <h4>
            {"Project Start Date: 2022-01-08 & Expect Delivery Date: &#8734"}
          </h4>
        </div>
      </main>

      <footer className={styles.footer}>{"Created by rNLKJA & kwitter"}</footer>
    </div>
  );
};

export default Home;
